apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: npminstall
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build
      runAfter:
        - tests
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: docker-build
            image: docker:27-cli
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              docker build -t tax-calculator .
      workspaces:
        - name: source
          workspace: shared-workspace
